server:
  port: 8086

spring:
  application:
    name: simple-bdd-automation
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 10GB #Size limit for a single file. The maximum allowed size of a single uploaded file. i.e. 1MB Priority 2, This config also works for limit the upload Maximum size.
      max-request-size: 100GB #Each request total file size limit. The maximum allowed size of a complete request. i.e. 100KB Priority 1, Limit the multipart/form-data file upload Maximum size.
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ


springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  packages-to-scan: ps.demo
  show-actuator: false
  model-and-view-allowed: true
#  override-with-generic-response: true

---

spring:
  config:
    activate:
      on-profile: dev




